services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - main
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/postgresql_rss_feed

  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    networks:
      - main
    depends_on:
      - postgres
    ports:
      - 8000:8000
    restart: always

  redis:
    container_name: redis
    image: redis:7.2
    networks:
      - main
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/redis_rss_feed


networks:
  main:

volumes:
  postgres_data:
  redis_data: