# Generated by Django 4.2.5 on 2023-10-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_bookmark_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
