# Generated by Django 4.2.5 on 2023-09-27 11:00

from django.db import migrations, models
import django.db.models.deletion
import feeder.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=25)),
                ('image_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XmlLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_link', models.URLField(unique=True)),
                ('channel_parser', models.CharField(max_length=50)),
                ('items_parser', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(blank=True, to='feeder.category')),
                ('rss_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feeder.type')),
            ],
        ),
        migrations.CreateModel(
            name='SearchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.channel')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('source', models.URLField(blank=True, null=True)),
                ('guid', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.channel')),
            ],
            bases=(feeder.mixins.ItemsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('guid', models.TextField()),
                ('audio_file_url', models.URLField(max_length=500)),
                ('image_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=25, null=True)),
                ('explicit', models.CharField(blank=True, max_length=10, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.channel')),
            ],
            bases=(feeder.mixins.ItemsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='channel',
            name='xml_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feeder.xmllink'),
        ),
    ]
