# Generated by Django 4.2.5 on 2023-10-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name': 'Podcats Episode', 'verbose_name_plural': 'Podcats Episode'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='searchcount',
            options={'verbose_name': 'Search Count', 'verbose_name_plural': 'Search Counts'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='xmllink',
            options={'verbose_name': 'Xml Link', 'verbose_name_plural': 'Xml Links'},
        ),
    ]
