# Generated by Django 4.2.5 on 2023-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_alter_episode_guid_alter_news_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='last_item_guid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
