# Generated by Django 4.2.5 on 2023-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_alter_channel_last_item_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
