# Generated by Django 4.2.5 on 2023-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_action_notification_broadcast_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='broadcast_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
