# Generated by Django 4.2.5 on 2023-10-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='userlastactivity',
            options={'verbose_name': 'User Last Activity', 'verbose_name_plural': 'Users Last Activity'},
        ),
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
    ]
