# Generated by Django 4.2.5 on 2023-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_broadcast_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='broadcast_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
