# Generated by Django 4.2.5 on 2023-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_notification_broadcast_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='broadcast_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
