# Generated by Django 4.2.5 on 2023-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_notification_broadcast_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
