# Generated by Django 4.2.5 on 2023-10-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notification_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
    ]
