# Generated by Django 4.2.5 on 2023-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, null=True),
        ),
    ]
